# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "19e0c4fbcf358179cdc16407e4be5497"
name = "order-app"
handle = "order-app-67"
application_url = "https://instructors-homeless-invited-bids.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-ac056c65.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products,write_customers,write_inventory,write_orders,write_products"

[auth]
redirect_urls = [
  "https://instructors-homeless-invited-bids.trycloudflare.com/auth/callback",
  "https://instructors-homeless-invited-bids.trycloudflare.com/auth/shopify/callback",
  "https://instructors-homeless-invited-bids.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
