# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d2550c1d4d2c223983d0ffdfc866c316"
name = "order-tracking-app"
handle = "order-tracking-app-10"
application_url = "https://order-tracking-app-deploy.vercel.app/?host=admin.myshopify.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "dev-store-testing-apps.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products,write_customers,write_inventory,write_orders,write_products"

[auth]
redirect_urls = [
  "https://order-tracking-app-deploy-jsc9cs634-jawad-akrams-projects.vercel.app/api/auth",
  "https://order-tracking-app-deploy-jsc9cs634-jawad-akrams-projects.vercel.app/auth/callback",
  "https://order-tracking-app-deploy-jsc9cs634-jawad-akrams-projects.vercel.app/api/auth/callback",
  "https://order-tracking-app-deploy-jsc9cs634-jawad-akrams-projects.vercel.app/auth/shopify/callback",
  "https://order-tracking-app-deploy.vercel.app/api/auth?host=admin.myshopify.com"
]

[webhooks]
api_version = "2024-07"

[app_proxy]
url = "https://order-tracking-app-deploy.vercel.app/api/auth?host=admin.myshopify.com"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false
