# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "20e54f04f6afbfbada0064024fc3c1a1"
name = "order-tracking-app"
handle = "order-tracking-app-9"
application_url = "https://malta-sheets-incident-triumph.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-store-testing-apps.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products,write_customers,write_inventory,write_orders,write_products"

[auth]
redirect_urls = [
  "https://malta-sheets-incident-triumph.trycloudflare.com/auth/callback",
  "https://malta-sheets-incident-triumph.trycloudflare.com/auth/shopify/callback",
  "https://malta-sheets-incident-triumph.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[app_proxy]
url = "https://malta-sheets-incident-triumph.trycloudflare.com"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false
